### ISSUE TITLE
Handle invalid (null terminated) Vorbis comments

### ISSUE THREAD

**Issue by replicant0wnz** [thebigmunch/audio-metadata#10]
Got a new one :-D 
```
Traceback (most recent call last):
File "/usr/local/bin/gms", line 11, in <module>
sys.exit(run())
File "/usr/local/lib/python3.6/dist-packages/google_music_scripts/cli.py", line 968, in run
args.func(args)
File "/usr/local/lib/python3.6/dist-packages/google_music_scripts/commands.py", line 465, in do_upload
delete_on_success=args.delete_on_success
File "/usr/local/lib/python3.6/dist-packages/google_music_scripts/core.py", line 334, in upload_songs
no_sample=no_sample
File "/usr/local/lib/python3.6/dist-packages/google_music/clients/musicmanager.py", line 245, in upload
track_info = mm_calls.Metadata.get_track_info(song)
File "/usr/local/lib/python3.6/dist-packages/google_music_proto/musicmanager/calls.py", line 297, in get_track_info
track.track_number = int(track_split[0])
ValueError: invalid literal for int() with base 10: '1\x00'
```
I added a `print` statement at line 259 on `google_music_proto/musicmanager/calls.py` to get the offending file. Here's the FLAC header for it (kinda big due to embedded image):

http://dallaslamers.org/bad_flac.txt

**Comment by thebigmunch** [comment]
PS Thanks for finding me more files that break things ^_^

People truly don't understand how much we programmers want/need them.

**Comment by thebigmunch** [comment]
Ok, so, just for future reference, I tested with Google's Music Manager for shits and giggles. It strips null bytes somewhere along the way. Not sure I'd do that since audio-metadata would be throwing exceptions in this particular case in the future, but it's nice to know these quirks.

**Comment by thebigmunch** [comment]
I don't think there's actually anything I can do about this one but pass it through. I'll probably just add a try/except to google-music-proto where the exception occurs. If I end up trying to add a number field class for vorbis comments, I could handle this particular case there.

**Comment by replicant0wnz** [comment]
Think I'm just gonna run my entire collection through a tag "fixer" or just write my own. Thanks for taking a look!

**Comment by replicant0wnz** [comment]
Quick hack:

https://github.com/replicant0wnz/strip_null
