### ISSUE TITLE
Support MP3 files with no Xing header if more than 1 MPEG frames found

### ISSUE THREAD

**Issue by lowlow---** [thebigmunch/audio-metadata#5]
While uploading my collection with:
`gms up -u somename -v --debug /srv/library/music`

I encounter with the following error, while I used the 
```
Traceback (most recent call last):
   File "/usr/local/lib/venv.google-music-script/bin/gms", line 10, in <module>
      sys.exit(run())
  File "/usr/local/lib/venv.google-music-script/lib/python3.7/site-packages/google_music_scripts/cli.py", line 920, in run
    DISPATCH[command](args)
  File "/usr/local/lib/venv.google-music-script/lib/python3.7/site-packages/google_music_scripts/commands.py", line 364, in do_upload
    if generate_client_id(song) not in google_client_ids:
  File "/usr/local/lib/venv.google-music-script/lib/python3.7/site-packages/google_music_proto/musicmanager/utils.py", line 18, in generate_client_id
    song = audio_metadata.load(song)
  File "/usr/local/lib/venv.google-music-script/lib/python3.7/site-packages/audio_metadata/api.py", line 82, in load
    return parser_cls.load(fileobj)
  File "/usr/local/lib/venv.google-music-script/lib/python3.7/site-packages/audio_metadata/formats/mp3.py", line 519, in load
    self.streaminfo = MP3StreamInfo.load(self._obj)
  File "/usr/local/lib/venv.google-music-script/lib/python3.7/site-packages/audio_metadata/formats/mp3.py", line 406, in load
    raise InvalidFormat("Missing XING header and insufficient MPEG frames.")
audio_metadata.exceptions.InvalidFormat: Missing XING header and insufficient MPEG frames
```

Although "verbose" and "debug" gms options have been activated, not much additional info is reported ...

Here is my config in a Python 3.7 with a virtualenv: 
``` 
Package                Version
---------------------- -----------
ansimarkup             1.4.0
appdirs                1.4.3
attrs                  18.2.0
audio-metadata         0.4.0
better-exceptions-fork 0.2.1.post6
bidict                 0.17.5
bitstruct              6.0.0
certifi                2019.3.9
chardet                3.0.4 
colorama               0.4.1
google-music           3.0.1
google-music-proto     2.4.0
google-music-scripts   4.0.1
google-music-utils     2.1.0
idna                   2.8
loguru                 0.2.5
marshmallow            2.19.2
more-itertools         4.3.0
multidict              4.5.2
natsort                6.0.0
oauthlib               3.0.1
pendulum               2.0.4
pip                    19.0.3
pprintpp               0.4.0
protobuf               3.7.1
Pygments               2.4.0
python-dateutil        2.8.0
pytzdata               2019.1
requests               2.21.0
requests-oauthlib      1.2.0
setuptools             40.8.0
six                    1.12.0
tenacity               5.0.4
tomlkit                0.5.3
urllib3                1.24.3
wrapt                  1.11.1
```

Unable to find so far to find the file generating this error ...

**Comment by thebigmunch** [comment]
Transferred to audio-metadata repo.

Yeah, I got sidetracked by an injury before I got to release some logging changes/additions to the dependency stack that would help identify the file. I'm back to developing, just having gotten to releasing those changes yet.

For now, you can run [this script](https://gist.github.com/thebigmunch/c80560c789ce72d46db301e15c265082) in a directory to recursively check for audio files that fail to load with audio-metadata.

Feel free to post link/files here or by email so I can check them out.

**Comment by lowlow---** [comment]
Seems the issue is on my side, one of my file appears to be broken, the file size is nearly null (4k) ...

I've altered `google_music_scripts/commands.py` in such way to ignore failing files:

```
...
20          import audio_metadata
...

362         existing_songs = []
363         google_client_ids = {song.get('clientId', '') for song in get_google_songs(mc)}
364         for song in local_songs:
365             try:
366                 if generate_client_id(song) not in google_client_ids:
367                     missing_songs.append(song)
368                 else:
369                     existing_songs.append(song)
370             except audio_metadata.exceptions.InvalidFormat:
371                 logger.info("%s is not a valid file" %  song)

362         existing_songs = []
363         google_client_ids = {song.get('clientId', '') for song in get_google_songs(mc)}
364         for song in local_songs:
365             try:
366                 if generate_client_id(song) not in google_client_ids:
367                     missing_songs.append(song)
368                 else:
369                     existing_songs.append(song)
370             except audio_metadata.exceptions.InvalidFormat:
371                 logger.info("%s is not a valid file" %  song)

....
....

**Comment by thebigmunch** [comment]
Well, that doesn't necessarily mean it's broken. I'd like to take a look at it anyway just to check it out.

**Comment by lowlow---** [comment]
Here is the file...

Mar 14 mai 2019, à 11:11, thebigmunch a écrit :

**Comment by thebigmunch** [comment]
If you tried to attach it to the issue comment through email, I don't believe that works. You'd have to attach it through the web interface or email it to me directly at mail@thebigmunch.me.

**Comment by thebigmunch** [comment]
The file may be broken in that the song the metadata points to is supposed to be over 3 minutes long, not a fraction of a second, but it's actually a valid MP3 file. It only has 2 MPEG frames, though, which is below the threshold I've set for when an MP3 doesn't have a Xing header. But this file really should be supported by audio-metadata, so I'm going to work on changing up the code a bit to cover this kind of case. So, it should just work in a future release.
